name: CI (submodule, no cache)

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (with submodules)
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node (no cache)
        uses: actions/setup-node@v4
        with:
          node-version: "18.x"

      - name: Install deps
        working-directory: loreweaver
        run: |
          if [ -f package-lock.json ]; then
            npm ci
          else
            npm install
          fi

      - name: Build (tolerant)
        working-directory: loreweaver
        run: |
          if [ -f Gruntfile.js ]; then
            npx grunt || true
          else
            mkdir -p dist && echo ok > dist/.keep
          fi

      - name: Upload artifact (if any)
        if: ${{ hashFiles('loreweaver/dist/**') != '' }}
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: loreweaver/dist

