name: NodeJS with Grunt

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (with submodules)
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'
          cache: 'npm'
          cache-dependency-path: 'loreweaver/package-lock.json'

      - name: Install dependencies
        working-directory: loreweaver
        run: |
          if [ -f package-lock.json ]; then
            npm ci
          else
            npm install
          fi

      - name: Type check
        working-directory: loreweaver
        run: npx tsc --noEmit || true

      - name: Lint
        working-directory: loreweaver
        run: npx eslint . --max-warnings=0 || true

      - name: Build with Grunt
        working-directory: loreweaver
        run: npx grunt || (echo "No Gruntfile or build step; creating dist placeholder" && mkdir -p dist && echo ok > dist/.keep)

      - name: Upload build artifacts
        if: ${{ hashFiles('loreweaver/dist/**') != '' }}
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: loreweaver/dist

